### ISSUE TITLE
span.required issues

### ISSUE THREAD

**Issue by alanhogan** [zeelot/kohana-yform#27] opened 2010-08-11 01:49 UTC
`<span class="required">`
1. Is output even when empty (not required). This is problematic because attempts to style it regardless of text, e.g. loading a background image of a stylized asterisk, and attempts to detect presence of 'required' labels via the DOM, will be incorrect.
2. There is always whitespace between the label and this span. This end user should be able to decide whether or not a space should be the first character in the 'required' text, instead. It is probably impossible to reliably wish away this extra whitespace with CSS.

**Comment by zeelot** [comment] 2010-08-11 23:08
1 is not reproducible  and 2 is a duplicate of #20

**Closed as completed by zeelot** 2010-08-11 23:09 UTC
Labels: Assigned, Bug
